# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Ubuntu x64

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Linux
    strategy:
      matrix:
        dotnet-version: [ 9.0.x ]
    # Service containers to run with `runner-job`
#    services:
#      # Label used to access the service container
#      redis:
#        # Docker Hub image
#        image: redis
#        # Set health checks to wait until redis has started
#        options: >-
#          --health-cmd "redis-cli ping"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          # Maps port 6379 on service container to the host
#          - 6379:6379
          
    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore ./src/HybridRedisCache.sln

    - name: Build solution
      run: dotnet build -c Release ./src/HybridRedisCache.sln --verbosity minimal

    - name: Run tests
      run: dotnet test -c Release ./src/HybridRedisCache.sln --verbosity normal --no-build --no-restore

      # a new Redis client.
#      env:
#          # The hostname used to communicate with the Redis service container
#          REDIS_HOST: localhost
#          # The default Redis port
#          REDIS_PORT: 6379
